/**
 * The generated blocks inside `README.md`: the badges row and the release notes.
 *
 * Both repository hosts and npm render the README, so the README must not carry
 * hand-maintained values that go stale (badge URLs did: a freshly published
 * package showed "package not found" from a cached registry result). The blocks
 * are generated - `package.json` and `CHANGELOG.md` stay the source of truth -
 * and can be verified with `check: true`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import {
  CHANGELOG_END,
  CHANGELOG_START,
  changelogDate,
  changelogSection,
} from "./changelog-section.mjs";

export const BADGES_START = "<!-- badges:start -->";
export const BADGES_END = "<!-- badges:end -->";

function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

/** Version of the package that owns the current working directory. */
export function packageVersion(packagePath = "package.json") {
  const pkg = readJson(packagePath);
  if (typeof pkg.version !== "string" || !pkg.version) {
    throw new Error(`${packagePath} has no "version"`);
  }
  return pkg.version;
}

/** `owner`/`repo` parsed from the package's GitHub repository URL. */
export function repositorySlug(packagePath = "package.json") {
  const pkg = readJson(packagePath);
  const url = typeof pkg.repository === "string" ? pkg.repository : pkg.repository?.url;
  const match = /github\.com[/:]([^/]+)\/([^/]+?)(?:\.git)?\/?$/.exec(String(url ?? ""));
  if (!match) throw new Error(`${packagePath} has no GitHub repository URL to build badges from`);
  return { owner: match[1], repo: match[2] };
}

/**
 * Badges row: npm version, license, CI status, changelog link.
 *
 * The license badge reads the LICENSE file on GitHub instead of the npm
 * registry: it cannot turn red while the registry CDN still serves a cached
 * "package not found" from before the first publish.
 */
export function badgesBlock(packageName, owner, repo) {
  return [
    "<!-- Generated by pi-release sync-readme from package.json; edit package.json, not this block. -->",
    `[![npm](https://img.shields.io/npm/v/${packageName})](https://www.npmjs.com/package/${packageName})`,
    `[![license](https://img.shields.io/github/license/${owner}/${repo})](LICENSE)`,
    `[![CI](https://github.com/${owner}/${repo}/actions/workflows/ci.yml/badge.svg)](https://github.com/${owner}/${repo}/actions/workflows/ci.yml)`,
    "[![changelog](https://img.shields.io/badge/changelog-Keep%20a%20Changelog-blue)](CHANGELOG.md)",
  ].join("\n");
}

/** Block content without the surrounding markers. */
export function releaseNotesBlock(version, date, section) {
  return [
    "<!-- Generated by pi-release sync-readme-changelog; edit CHANGELOG.md, not this block. -->",
    `**${version}${date ? ` - ${date}` : ""}**`,
    "",
    section,
    "",
    "Full history and all versions: [CHANGELOG.md](./CHANGELOG.md)",
  ].join("\n");
}

/** Locates a marker pair; throws when the markers are broken. */
function markers(readme, readmePath, start, end) {
  const from = readme.indexOf(start);
  const to = readme.indexOf(end);

  if (from === -1 || to === -1) return null;
  if (to < from) throw new Error(`${readmePath} has the ${start}/${end} markers in the wrong order`);
  if (readme.indexOf(start, from + 1) !== -1 || readme.indexOf(end, to + 1) !== -1) {
    throw new Error(`${readmePath} has duplicate ${start}/${end} markers`);
  }
  return { from, to };
}

/** Replaces the content between the markers, or verifies it when `check` is set. */
function applyBlock(readmePath, readme, { from, to }, start, end, block, check, label) {
  if (check) {
    const current = readme.slice(from + start.length, to).trim();
    if (current !== block) {
      throw new Error(`${readmePath} ${label} is stale - run "npm run readme" and commit it`);
    }
    return `${readmePath} ${label} is up to date.`;
  }

  writeFileSync(readmePath, readme.slice(0, from) + `${start}\n${block}\n${end}` + readme.slice(to + end.length), "utf8");
  return `${readmePath} ${label} updated.`;
}

/**
 * Rewrites the badges row of `readmePath` from `package.json`. Repositories
 * without the markers are skipped, so the block is opt-in per repository.
 */
export function syncBadges({ readmePath = "README.md", packagePath = "package.json", check = false } = {}) {
  const readme = readFileSync(readmePath, "utf8");
  const where = markers(readme, readmePath, BADGES_START, BADGES_END);
  if (!where) return null;

  const { owner, repo } = repositorySlug(packagePath);
  const packageName = readJson(packagePath).name;
  if (typeof packageName !== "string" || !packageName) {
    throw new Error(`${packagePath} has no "name"`);
  }

  return applyBlock(readmePath, readme, where, BADGES_START, BADGES_END, badgesBlock(packageName, owner, repo), check, "badges block");
}

/** Rewrites the release-notes block of `readmePath` from `CHANGELOG.md`. */
export function syncChangelogBlock({
  readmePath = "README.md",
  changelogPath = "CHANGELOG.md",
  packagePath = "package.json",
  check = false,
} = {}) {
  const version = packageVersion(packagePath);
  const changelog = readFileSync(changelogPath, "utf8");
  const section = changelogSection(changelog, version);
  if (!section) throw new Error(`${changelogPath} has no ## [${version}] section`);

  const readme = readFileSync(readmePath, "utf8");
  const where = markers(readme, readmePath, CHANGELOG_START, CHANGELOG_END);
  if (!where) throw new Error(`${readmePath} needs the ${CHANGELOG_START} / ${CHANGELOG_END} markers`);

  const block = releaseNotesBlock(version, changelogDate(changelog, version), section);
  return applyBlock(readmePath, readme, where, CHANGELOG_START, CHANGELOG_END, block, check, `release-notes block (${version})`);
}

/** Syncs every generated README block. Returns the log lines for the caller. */
export function syncReadme(options = {}) {
  return [syncBadges(options), syncChangelogBlock(options)].filter(Boolean).join("\n");
}

/**
 * Body for a GitHub release: the CHANGELOG section of the package version.
 * Throws when the section is missing.
 */
export function releaseNotes(packagePath = "package.json", changelogPath = "CHANGELOG.md") {
  const version = packageVersion(packagePath);
  const section = changelogSection(readFileSync(changelogPath, "utf8"), version);
  if (!section) throw new Error(`${changelogPath} has no ## [${version}] section`);

  return { version, notes: `### Changes in ${version}\n\n${section}\n` };
}