/**
 * The release-notes block inside `README.md`.
 *
 * Both repository hosts and npm render the README, so every repository shows
 * the changes of its current version there instead of only linking to
 * `CHANGELOG.md`. The block is generated - `CHANGELOG.md` stays the single
 * source of truth - and can be verified with `check: true`.
 */

import { readFileSync, writeFileSync } from "node:fs";
import {
  CHANGELOG_END,
  CHANGELOG_START,
  changelogDate,
  changelogSection,
} from "./changelog-section.mjs";

/** Block content without the surrounding markers. */
export function releaseNotesBlock(version, date, section) {
  return [
    "<!-- Generated by pi-release sync-readme-changelog; edit CHANGELOG.md, not this block. -->",
    `**${version}${date ? ` - ${date}` : ""}**`,
    "",
    section,
    "",
    "Full history and all versions: [CHANGELOG.md](./CHANGELOG.md)",
  ].join("\n");
}

/** Version of the package that owns the current working directory. */
export function packageVersion(packagePath = "package.json") {
  const pkg = JSON.parse(readFileSync(packagePath, "utf8"));
  if (typeof pkg.version !== "string" || !pkg.version) {
    throw new Error(`${packagePath} has no "version"`);
  }
  return pkg.version;
}

/**
 * Rewrites the release-notes block of `readmePath` from `changelogPath`, or
 * verifies it when `check` is set. Returns the log line for the caller.
 * Throws when markers or the CHANGELOG section are missing, or when the
 * committed block is stale.
 */
export function syncReadmeChangelog({
  readmePath = "README.md",
  changelogPath = "CHANGELOG.md",
  packagePath = "package.json",
  check = false,
} = {}) {
  const version = packageVersion(packagePath);
  const changelog = readFileSync(changelogPath, "utf8");
  const section = changelogSection(changelog, version);
  if (!section) throw new Error(`${changelogPath} has no ## [${version}] section`);

  const readme = readFileSync(readmePath, "utf8");
  const start = readme.indexOf(CHANGELOG_START);
  const end = readme.indexOf(CHANGELOG_END);

  if (start === -1 || end === -1 || end < start) {
    throw new Error(`${readmePath} needs the ${CHANGELOG_START} / ${CHANGELOG_END} markers`);
  }
  if (readme.indexOf(CHANGELOG_START, start + 1) !== -1 || readme.indexOf(CHANGELOG_END, end + 1) !== -1) {
    throw new Error(`${readmePath} has duplicate ${CHANGELOG_START}/${CHANGELOG_END} markers`);
  }

  const block = releaseNotesBlock(version, changelogDate(changelog, version), section);

  if (check) {
    const current = readme.slice(start + CHANGELOG_START.length, end).trim();
    if (current !== block) {
      throw new Error(`${readmePath} release-notes block is stale - run "npm run readme" and commit it`);
    }
    return `${readmePath} release-notes block matches ${version}.`;
  }

  writeFileSync(
    readmePath,
    readme.slice(0, start) + `${CHANGELOG_START}\n${block}\n${CHANGELOG_END}` + readme.slice(end + CHANGELOG_END.length),
    "utf8",
  );
  return `Synced the ${version} release notes into ${readmePath}.`;
}

/**
 * Body for a GitHub release: the CHANGELOG section of the package version.
 * Throws when the section is missing.
 */
export function releaseNotes(packagePath = "package.json", changelogPath = "CHANGELOG.md") {
  const version = packageVersion(packagePath);
  const section = changelogSection(readFileSync(changelogPath, "utf8"), version);
  if (!section) throw new Error(`${changelogPath} has no ## [${version}] section`);

  return { version, notes: `### Changes in ${version}\n\n${section}\n` };
}